optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.00001,
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 400,
    initial_epochs : 10
}}

dataset : {
  train : { _base_: configs/dataset_configs/PretrainData.yaml,
            others: {subset: 'train', kpoints: 64}},
  val : { _base_: configs/dataset_configs/PretrainData.yaml,
            others: {subset: 'test', kpoints: 64}},
  test : { _base_: configs/dataset_configs/PretrainData.yaml,
            others: {subset: 'test', kpoints: 64}}}

model : {
  NAME: Point_MAE,
  group_size: 64,
  num_group: 128,
  loss: cdl2,
  transformer_config: {
    mask_ratio: 0.6,
    mask_type: 'rand',
    trans_dim: 768,
    encoder_dims: 768,
    depth: 24,
    drop_path_rate: 0.1,
    num_heads: 6,
    decoder_depth: 8,
    decoder_num_heads: 16,
  },
  }

npoints: 4096
total_bs : 128
step_per_update : 1
max_epoch : 400
